### ISSUE TITLE
Hello:) I'd like to ask a question

### ISSUE THREAD

**Issue by dwfault** [lucasg/lucasg.github.io#1]
Hello, I read your 《How Control Flow Integrity is implemented in Windows 10》. That's a great article and helps a lot.
I am writing to seek for help, you mentioned Process Hackers's peview.exe. I tried it but the newest version on Downloads@SourceForge  shows no CFG tab in the program window. I wonder if you could tell me where to get the newest one.
Thanks a lot :)

**Comment by lucasg** [comment]
I don't think there is a new release with my addition to `PeView`. You can try the "nightly" build (dev branch) which should incorporate it : https://wj32.org/processhacker/nightly.php

**Comment by dwfault** [comment]
Thanks very much!


原始邮件
发件人:lucasgnotifications@github.com
收件人:lucasg/lucasg.github.iolucasg.github.io@noreply.github.com
抄送:dwfaultdwfault@163.com; Authorauthor@noreply.github.com
发送时间:2017年4月13日(周四) 00:55
主题:Re: [lucasg/lucasg.github.io] Hello:) I'd like to ask a question (#1)


I don't think there is a new release with my addition to PeView. You can try the "nightly" build (dev branch) which should incorporate it : https://wj32.org/processhacker/nightly.php
